### ISSUE TITLE
add feature : scan command

### ISSUE THREAD

**Issue by limbo127** [cybergarage/go-redis#1]
Hello, can you add scan command ?
regards, 
Nicolas

**Comment by cybergarage** [comment]
@limbo127, I've added the SCAN interface as detailed below and released it along with the example server in version 1.4.3.

- [GenericCommandHandler::Scan](https://github.com/cybergarage/go-redis/blob/main/redis/handler.go) - Here, we've defined the interface for handling the SCAN command.
- [go-redis/examples/go-redisd/server/generic.go](https://github.com/cybergarage/go-redis/blob/main/examples/go-redisd/server/generic.go) - This example demonstrates how the SCAN interface is utilized in practice.

Please take a moment to check it out :-)
